---
version: "2.4"
services:
    client:
        build:
            context: ./Client
            args:
                SERVER_IP: "192.168.8.115:30300"
        container_name: client_amie
        env_file:
            - .env
        ports:
            - 5000:5000
        restart: unless-stopped
    server:
        build:
            context: ./Server
        container_name: server_amie
        env_file:
            - .env
        volumes:
            - ./secrets.json:/secrets.json
        ports:
            - 30300:8080
            - 52452:52452
        restart: unless-stopped
    svelteclient:
        build:
            context: ./Client-Svelte
        container_name: svelteclient
        env_file:
            - .env
        ports:
            - 5010:5000
        restart: unless-stopped
